language: go

go:
  - master # This uses automatically the latest version of go

install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install

script:
  - hugo # This commands builds your website on travis

after_success: |
    cd public
    git add .
    git commit -m 'Site push'
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/marksteele.github.io master
