language: python

install:
  - apt-get install python-pygments
  - apt-get install https://github.com/gohugoio/hugo/releases/download/v0.39/hugo_0.39_Linux-64bit.deb

script:
  - hugo # This commands builds your website on travis

after_success: |
    cd public
    git add .
    git commit -m 'Site push'
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/marksteele.github.io master
