baseURL = "https://www.control-alt-del.org/"
languageCode = "en-us"
defaultContentLanguage = "en"

title = "Mark's Blargh"
theme = "dream-plus"


pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

enableRobotsTXT = true
enableEmoji=true


[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = false
  latexDashes = true
  smartypants = false
  factions = true
  extensions = ["hardLineBreak"]

[params]
    featured_image = "/images/IMG_1191.jpg"
    Subtitle = "Mark's blargh"
    description = "The ramblings of Mark, in blargh format."
    author = "Mark Steele"
    avatar = "/images/mark.jpg"
    motto = "Cogito Interruptus Vulgaris"
    enableToc = true
    enableShareCard = true
      
    enableColorBG= false
    bgBlur = "0px"
    bgImage = "/images/IMG_1191.jpg"
    
    #Post-displaying Settings
    enableTags = false
    enableCategories = true
    itemsPerPage = 4
    contentType = "post"
    twitterEmoji=true
  	siteStartYear = 1999
    
[social]
	email = "mark@control-alt-del.org"
	github = "marksteele"
	twitter = "markrsteele" 
