baseURL = "https://www.control-alt-del.org/"
title = "Mark's Blargh"
theme = "dream-plus"
paginate = 8

enableEmoji=true
enableRobotsTXT = true

disqusShortname=""

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

languageCode = "en-us"
defaultContentLanguage = "en"



[params]
	contentType = "posts"
	siteStartYear = 1999
	featured_image = "/images/IMG_1191.jpg"

	[params.author]
		name = "Mark Steele"
		description = "The ramblings of Mark, in blargh format."
		avatar = "/images/mark.jpg"
		motto = "Cogito Interruptus Vulgaris"


	[params.features]
		twitterEmoji = false
		toc = false
		shareCard = true
		customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]
		customJS = ["https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.4.0/jquery.fancybox.min.js"]

	[params.background]
		bgBlur = "0px"
		bgList = ["/images/IMG_1191.jpg"]

	[params.tags]
		enabled = false

	#Categories settings
	[params.categories]
		enabled = true


[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = false
  latexDashes = true
  smartypants = false
  factions = true
  extensions = ["hardLineBreak"]  
    
[social]
	email = "mark@control-alt-del.org"
	github = "marksteele"
	twitter = "markrsteele" 
  
