name: build-blog
on: [push]
jobs:
  do-the-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-get install python-pygments imagemagick
      - run: sudo wget -qO hugo_0.55.6_Linux-64bit.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
      - run: sudo dpkg -i hugo_0.55.6_Linux-64bit.deb
      - shell: bash
        run: |
          for i in `find static/images/galleries -type f ! -name "*-thumb.jpg" -name "*.jpg"`; do echo $i; if [ -f ${i%.*}-thumb.jpg ]; then continue; fi; convert $i -thumbnail 100x100 ${i%.*}-thumb.jpg; done
      - run: hugo
      - shell: bash
        run: |
          cd public
          git add .
          git status
          git commit -m 'Site push'
          git config user.email "mark@control-alt-del.org"
          git config user.name "Mark Steele"
          git push https://marksteele:${{ secrets.PAT }}@github.com/marksteele/marksteele.github.io master
