name: build-blog
on: [push]
jobs:
  do-the-thing:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python-pygments imagemagick
      - run: sudo wget -qO hugo_0.55.6_Linux-64bit.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
      - run: sudo dpkg -i hugo_0.55.6_Linux-64bit.deb
      - run: git submodule foreach -q --recursive 'branch="$(git config -f $toplevel/.gitmodules submodule.$name.branch)"; [ -z "$branch" ] && git checkout master || git checkout $branch'
